{% set name = "liecasadi" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/liecasadi-{{ version }}.tar.gz
  sha256: c469d6477301954450207fadf9ffa5cd35968785834ef26c10b20e33bb195763

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - wheel
    - setuptools >=45
    - setuptools-scm >=6.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21
    - casadi

test:
  imports:
    - liecasadi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ami-iit/liecasadi
  summary: Rigid transform using Lie groups, written in CasADi!
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - Giulero
