{% set name = "liecasadi" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/liecasadi-{{ version }}.tar.gz
  sha256: 27fe534ea96dd4dffcecfdfb65ae484e09b45e7691cb8e2bf6d7fc62edd33eee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - wheel
    - setuptools >=45
    - setuptools-scm >=6.0
    - pip
  run:
    - python >=3.8
    - numpy >=1.21
    - casadi

test:
  imports:
    - liecasadi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ami-iit/liecasadi
  summary: Rigid transform using Lie groups, written in CasADi!
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - Giulero
